language: java
sudo: required
dist: trusty
group: edge

matrix:
  fast_finish: true

  include:
    # JDK 8
    - jdk: oraclejdk8
      env: JDK_RELEASE='JDK 1.8'

script:
- ./gradlew build

after_success:
  - ./gradlew jacocoRootReport && bash <(curl -s https://codecov.io/bash) || true

env:
  global:
    - CODECOV_TOKEN=caadc54b-42b3-4f8f-bd07-707220006eec